In [1]:
import numpy as np 
import time


# Goal
- Reviwe the features of Numpy and Pyhton that are used  for LR or others cases

# Python and Numpy
Python is the programming language .It has a set of numeric data types and arithmetic operations. NumPy is a library that extends the base capabilities of python to add a richer data set including more numeric types, vectors, matrices, and many matrix functions. NumPy and python  work together fairly seamlessly. Python arithmetic operators work on NumPy data types and many NumPy functions will accept python data types.

# Vector
Vectors, as you will use them in this course, are ordered arrays of numbers. In notation, vectors are denoted with lower case bold letters such as $\mathbf{x}$.  The elements of a vector are all the same type. A vector does not, for example, contain both characters and numbers. The number of elements in the array is often referred to as the *dimension* though mathematicians may prefer *rank*. The vector shown has a dimension of $n$. The elements of a vector can be referenced with an index. In math settings, indexes typically run from 1 to n. In computer science and these labs, indexing will typically run from 0 to n-1.  In notation, elements of a vector, when referenced individually will indicate the index in a subscript, for example, the $0^{th}$ element, of the vector $\mathbf{x}$ is $x_0$. Note, the x is not bold in this case. 

# NumPy Arrays
NumPy's basic data structure is an indexable, n-dimensional * array * containing elements of the same type (`dtype`). Right away, you may notice we have overloaded the term 'dimension'. Above, it was the number of elements in the vector, here, dimension refers to the number of indexes of an array. A one-dimensional or 1-D array has one index.

# Vector Creation
Data creation routines in NumPy will generally have a first parameter which is the shape of the object. This can either be a single value for a 1-D result or a tuple (n,m,...) specifying the shape of the result. Below are examples of creating vectors using these routines.


In [7]:
a=np.zeros(4)
print(f"np.zeros(4): a={a}, a.shape= {a.shape}, a data type={a.dtype}")
a=np.zeros((4,0))
print(f"np.zeros(4,0): a={a},a shape={a.shape}, a datatype = {a.dtype}")

a=np.random.random_sample(4)
print(a)

np.zeros(4): a=[0. 0. 0. 0.], a.shape= (4,), a data type=float64
np.zeros(4,0): a=[],a shape=(4, 0), a datatype = float64
[0.84702424 0.54341832 0.79820742 0.09233504]


Some data creation routines do not take a shape tuple:

In [11]:
a=np.arange(4.)
print(f"a={a}\n shape={a.shape}")
a=np.random.rand(4)
a

a=[0. 1. 2. 3.]
 shape=(4,)


array([0.69472151, 0.82952113, 0.65784414, 0.74532647])

values can be specified manually as well. 

In [15]:
a=np.array([5,4,3,2,1])
print(f"a={a}\nshape={a.shape}, \ndim={a.ndim}\n\n")

a=np.array([[1,2],[3,4],[5,66]])
print(f"a={a}\nshape={a.shape}, \ndim={a.ndim}\n\n")



a=[5 4 3 2 1]
shape=(5,), 
dim=1


a=[[ 1  2]
 [ 3  4]
 [ 5 66]]
shape=(3, 2), 
dim=2




# Operations on Vectors

### Indexing 
Elements of vectors can be accessed via indexing and slicing. NumPy provides a very complete set of indexing and slicing capabilities. We will explore only the basics needed for the course here. Reference [Slicing and Indexing](https://NumPy.org/doc/stable/reference/arrays.indexing.html) for more details.  
**Indexing** means referring to *an element* of an array by its position within the array.  
**Slicing** means getting a *subset* of elements from an array based on their indices.  
NumPy starts indexing at zero so the 3rd element of an vector $\mathbf{a}$ is `a[2]`.



In [21]:
a= np.arange(10)
print(a)
for i in a:
    print(i,end=" ")
print()
print(a[-1])

try: 
    c=a[10]
except Exception as e:
    print(e)

[0 1 2 3 4 5 6 7 8 9]
0 1 2 3 4 5 6 7 8 9 
9
index 10 is out of bounds for axis 0 with size 10


### Slicing
Slicing creates an array of indices using a set of three values (`start:stop:step`). A subset of values is also valid. Its use is best explained by example:

In [27]:
a=np.arange(10)
print(f"{a[2:7:2]}")
print(a[3:])
print(a[:3:2])

[2 4 6]
[3 4 5 6 7 8 9]
[0 2]


### Single vector operations
There are a number of useful operations that involve operations on a single vector.

In [32]:
b=-a
b
print(np.sum(a))
print(np.mean(a))
b=a**2
b

45
4.5


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

### 3.4.4 Vector Vector element-wise operations
Most of the NumPy arithmetic, logical and comparison operations apply to vectors as well. These operators work on an element-by-element basis. For example 
$$ c_i = a_i + b_i $$

In [33]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a + b}")

Binary operators work element wise: [0 0 6 8]


In [34]:
#try a mismatched vector operation
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


### Vector Vector dot product
The dot product is a mainstay of Linear Algebra and NumPy. This is an operation used extensively in this course and should be well understood. The dot product is shown below.

The dot product multiplies the values in two vectors element-wise and then sums the result.
Vector dot product requires the dimensions of the two vectors to be the same. 

Let's implement our own version of the dot product below:

**Using a for loop**, implement a function which returns the dot product of two vectors. The function to return given inputs $a$ and $b$:
$$ x = \sum_{i=0}^{n-1} a_i b_i $$
Assume both `a` and `b` are the same shape.



In [35]:
def my_dot(a,b):
    """_summary_

    Args:
        a (_type_): _description_
        b (_type_): _description_
    """
    x=0
    for i in range(a.shape[0]):
        x+=(a[i]*b[i])
    return x

In [36]:
a=np.array([1,2,3,4])
b=np.array([-1,4,2,3])
print(my_dot(a,b))

25


In [37]:
c=np.dot(a,b)
print(c)

25


### The Need for Speed: vector vs for loop
We utilized the NumPy  library because it improves speed memory efficiency. Let's demonstrate:


In [ ]:
np.random.seed(1)
a=np.random.rand(10000000)
b=np.random.rand(10000000)
tic=time.time()
c=np.dot(a,b)
toc=time.time()
print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")
c=toc-tic
tic=time.time()
c=my_dot(a,b)
toc=time.time()
d=toc-tic
print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms \n\n")
# print(f"Vectorize operation is faster that loop version is around {((d*1000/c)*100):.4f}%")
del(a);del(b) 
 


np.dot(a, b) =  2501072.5817
Vectorized version duration: 8.2147 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 2267.8635 ms 




So, vectorization provides a large speed up in this example. This is because NumPy makes better use of available data parallelism in the underlying hardware. GPU's and modern CPU's implement Single Instruction, Multiple Data (SIMD) pipelines allowing multiple operations to be issued in parallel. This is critical in Machine Learning where the data sets are often very large.

# Matrices

## Abstract
Matrices, are two dimensional arrays. The elements of a matrix are all of the same type. In notation, matrices are denoted with capitol, bold letter such as $\mathbf{X}$. In this and other labs, `m` is often the number of rows and `n` the number of columns. The elements of a matrix can be referenced with a two dimensional index. In math settings, numbers in the index typically run from 1 to n. In computer science and these labs, indexing will run from 0 to n-1.

## Matrix Creation
The same functions that created 1-D vectors will create 2-D or n-D arrays. Here are some examples
Below, the shape tuple is provided to achieve a 2-D result. Notice how NumPy uses brackets to denote each dimension. Notice further than NumPy, when printing, will print one row per line.


In [46]:
a=np.array([[5],[4],[3]]);
print(f"a={a},shape={a.shape}")

a=np.arange(20).reshape(-1,10)
print(a)

a=[[5]
 [4]
 [3]],shape=(3, 1)
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [51]:
matrix1=np.array([[1,2],[3,4]])
print(matrix1)
matrix2=np.zeros((3,3))
print(matrix2)
matrix3=np.ones((2,4))
print(matrix3)

matrix4=np.eye(3)
print(matrix4)

matrix5=np.arange(9).reshape(3,3)
print(matrix5)


[[1 2]
 [3 4]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Basic Matrix Operations
NumPy provides very efficient operations for matrices:

In [52]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A+B)
print(A-B)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [53]:
print(2*A) # Scalar multiplication


[[2 4]
 [6 8]]


In [ ]:
print(A*B)  # Element-wise multiplication 
print(A/B) # ELement-wise division

[[ 5 12]
 [21 32]]


In [ ]:
print(A@B)  # Matrix multipication
print(np.dot(A,B)) # equivalent

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [57]:
print(A.T) # Transpose of A

[[1 3]
 [2 4]]


In [ ]:
print(np.linalg.det(A)) # determinant


-2.0000000000000004


In [ ]:
print(np.linalg.inv(A)) # inverse matrix 


[[-2.   1. ]
 [ 1.5 -0.5]]
